{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-gcp-vision-auth-key/versions/latest"
        fileName: "gcp-vision-auth-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest"
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-access-key-id/versions/latest"
        fileName: "aws-access-key-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-secret-access-key/versions/latest"
        fileName: "aws-secret-access-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-region-name/versions/latest"
        fileName: "aws-region-name"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-azure-form-recognizer-api/versions/latest"
        fileName: "azure-form-recognizer-api"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-azure-form-recognizer-key/versions/latest"
        fileName: "azure-form-recognizer-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-enabled/versions/latest"
        fileName: "auth-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest"
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest"
        fileName: "message-broker-connection-string"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_ocr.secretName }}
      type: Opaque
      data:
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "auth-enabled"
        key: auth-enabled
      - objectName: "azure-form-recognizer-api"
        key: azure-form-recognizer-api
      - objectName: "azure-form-recognizer-key"
        key: azure-form-recognizer-key
      - objectName: "aws-region-name"
        key: aws-region-name
      - objectName: "aws-secret-access-key"
        key: aws-secret-access-key
      - objectName: "aws-access-key-id"
        key: aws-access-key-id
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "gcp-vision-auth-key"
        key: gcp-vision-auth-key
{{- end }}
