{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "gcp-vision-auth-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-access-key-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-secret-access-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-region-name"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "azure-form-recognizer-api"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "azure-form-recognizer-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-enabled"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "kafka-sasl-username"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "kafka-sasl-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_ocr.secretName }}
      type: Opaque
      data:
        - objectName: "gcp-vision-auth-key"
          key: gcp-vision-auth-key
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
        - objectName: "aws-access-key-id"
          key: aws-access-key-id
        - objectName: "aws-secret-access-key"
          key: aws-secret-access-key
        - objectName: "aws-region-name"
          key: aws-region-name
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "azure-form-recognizer-api"
          key: azure-form-recognizer-api
        - objectName: "azure-form-recognizer-key"
          key: azure-form-recognizer-key
        - objectName: "auth-enabled"
          key: auth-enabled
        - objectName: "kafka-sasl-username"
          key: kafka-sasl-username
        - objectName: "kafka-sasl-password"
          key: kafka-sasl-password
{{- end }}