{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: gcp-vision-auth-key
      objectName: gcp-vision-auth-key
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: aws-access-key-id
      objectName: aws-access-key-id
    - key: aws-secret-access-key
      objectName: aws-secret-access-key
    - key: aws-region-name
      objectName: aws-region-name
    - key: azure-form-recognizer-api
      objectName: azure-form-recognizer-api
    - key: azure-form-recognizer-key
      objectName: azure-form-recognizer-key
    - key: auth-enabled
      objectName: auth-enabled
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: kafka-sasl-password
      objectName: kafka-sasl-password
    - key: kafka-sasl-username
      objectName: kafka-sasl-username
    secretName: {{ .Values.secrets.deps_ocr.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "gcp-vision-auth-key"
          objectType: secret

        - |
          objectName: "keycloak-certs-endpoint"
          objectType: secret

        - |
          objectName: "aws-access-key-id"
          objectType: secret

        - |
          objectName: "aws-secret-access-key"
          objectType: secret

        - |
          objectName: "aws-region-name"
          objectType: secret

        - |
          objectName: "azure-form-recognizer-api"
          objectType: secret

        - |
          objectName: "azure-form-recognizer-key"
          objectType: secret

        - |
          objectName: "auth-enabled"
          objectType: secret

        - |
          objectName: "message-broker-connection-string"
          objectType: secret

        - |
          objectName: "message-broker-driver"
          objectType: secret

        - |
          objectName: "kafka-sasl-password"
          objectType: secret

        - |
          objectName: "kafka-sasl-username"
          objectType: secret
{{- end }}