{{- if .Values.ocr_api_gateway_tesseract.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: tesseract-engin
  labels:
    {{- include "deps-ocr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ocr_api_gateway_tesseract.service.type }}
  ports:
    - port: {{ .Values.ocr_api_gateway_tesseract.service.port }}
      targetPort: {{ .Values.ocr_api_gateway_tesseract.container.portname }}
      protocol: {{ .Values.ocr_api_gateway_tesseract.service.protocol }}
      name: {{ .Values.ocr_api_gateway_tesseract.service.portname }}
  selector:
    {{- include "deps-ocr-api-gateway-tesseract.selectorLabels" . | nindent 4 }}
{{- end }}
