{{- if .Values.ocr_api_gateway_azure_form_recognizer.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: azure-form-recognizer-engin
  labels:
    {{- include "deps-ocr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ocr_api_gateway_azure_form_recognizer.service.type }}
  ports:
    - port: {{ .Values.ocr_api_gateway_azure_form_recognizer.service.port }}
      targetPort: {{ .Values.ocr_api_gateway_azure_form_recognizer.container.portname }}
      protocol: {{ .Values.ocr_api_gateway_azure_form_recognizer.service.protocol }}
      name: {{ .Values.ocr_api_gateway_azure_form_recognizer.service.portname }}
  selector:
    {{- include "deps-ocr-api-gateway-azure-form-recognizer.selectorLabels" . | nindent 4 }}
{{- end }}
