version: "3.4"

services:
  ocr-api-gateway:
    image: "ocr-api-gateway-dev"
    container_name: deps-ocr-gateway

  ocr-gateway-consumer:
    image: "ocr-api-gateway-dev"
    container_name: deps-ocr-gateway-consumer
    command: python -m deps_ocr_gateway consume

  tesseract-engin:
    image: "tesseract-engin-dev"
    container_name: deps-tesseract-engin

  # aws-textract-engin:
  #   image: "aws-textract-engin-dev"
  #   container_name: deps-aws-textract-engin
  #
  # gcp-vision-engin:
  #   image: "gcp-vision-engin-dev"
  #   container_name: deps-gcp-vision-engin
  #
  # azure-form-recognizer-engin:
  #   image: "azure-form-recognizer-engin-dev"
  #   container_name: deps-azure-form-recognizer-engin
