{{- if .Values.ocr_api_gateway_aws_textract.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: aws-textract-engin
  labels:
    {{- include "deps-ocr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ocr_api_gateway_aws_textract.service.type }}
  ports:
    - port: {{ .Values.ocr_api_gateway_aws_textract.service.port }}
      targetPort: {{ .Values.ocr_api_gateway_aws_textract.container.portname }}
      protocol: {{ .Values.ocr_api_gateway_aws_textract.service.protocol }}
      name: {{ .Values.ocr_api_gateway_aws_textract.service.portname }}
  selector:
    {{- include "deps-ocr-api-gateway-aws-textract.selectorLabels" . | nindent 4 }}
{{- end }}
