[tool.poetry]
name = "gcpvision-engine"
version = "0.2.0"
description = "GCPVision engine for extracting text from images."
authors = []
packages = [{include = "gcpvision_engine"}]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
Pillow = "^12.1.1"
protobuf = "^6.33.5"
google-cloud-vision = "^3.0.0"
pyasn1="^0.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

