apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-api-gateway-configmap
data:
  ENV: {{ .Values.ocr_api_gateway_settings.ENV }}
  PROJECT_VERSION: {{ .Values.ocr_api_gateway_settings.PROJECT_VERSION  | quote }}
  WORKERS: {{ .Values.ocr_api_gateway_settings.WORKERS  | quote }}
  RELOAD: {{ .Values.ocr_api_gateway_settings.RELOAD  | quote }}
  LOG_LEVEL: {{ .Values.ocr_api_gateway_settings.LOG_LEVEL  | quote }}
  MAX_REQUESTS: {{ .Values.ocr_api_gateway_settings.MAX_REQUESTS  | quote }}
  TIMEOUT: {{ .Values.ocr_api_gateway_settings.TIMEOUT  | quote }}
  OMP_THREAD_LIMIT: {{ .Values.ocr_api_gateway_settings.OMP_THREAD_LIMIT  | quote }}
  OCR_ENGINES_PREINIT: {{ .Values.ocr_api_gateway_settings.OCR_ENGINES_PREINIT  | quote }}
  OCR_ENABLE_CUDA_GPU: {{ .Values.ocr_api_gateway_settings.OCR_ENABLE_CUDA_GPU  | quote }}
  SENTRY_ENABLED: {{ .Values.ocr_api_gateway_settings.SENTRY_ENABLED  | quote }}
  SENTRY_TRACE_ENABLED: {{ .Values.ocr_api_gateway_settings.SENTRY_TRACE_ENABLED  | quote }}
  SENTRY_TRACES_SAMPLE_RATE: '{{ .Values.ocr_api_gateway_settings.SENTRY_TRACES_SAMPLE_RATE }}'
  DEBUG: {{ .Values.ocr_api_gateway_settings.DEBUG  | quote }}
  RABBITMQ_PORT: {{ .Values.ocr_api_gateway_settings.RABBITMQ_PORT  | quote }}
  VERIFY_SSL: {{ .Values.ocr_api_gateway_settings.VERIFY_SSL  | quote }}
  PAID_ENGINES_RESTRICTION_ENABLED: {{ .Values.ocr_api_gateway_settings.PAID_ENGINES_RESTRICTION_ENABLED  | default true | quote }}
  ENABLED_OCR_ENGINES: {{ .Values.ocr_api_gateway_settings.ENABLED_OCR_ENGINES  | quote }}
  PRIVILEGED_GROUP: {{ .Values.ocr_api_gateway_settings.PRIVILEGED_GROUP | quote }}
  AUTH_VERIFY_SSL: {{ .Values.ocr_api_gateway_settings.AUTH_VERIFY_SSL  | quote }}
  DOCUMENTATION_ENABLED: {{ .Values.ocr_api_gateway_settings.DOCUMENTATION_ENABLED  | quote }}
  KAFKA_GROUP_ID: {{ .Values.ocr_api_gateway_settings.KAFKA_GROUP_ID  | quote }}
  KAFKA_ENABLE_AUTO_COMMIT: {{ .Values.ocr_api_gateway_settings.KAFKA_ENABLE_AUTO_COMMIT | quote }}
  KAFKA_ENABLE_AUTO_OFFSET_STORE: {{ .Values.ocr_api_gateway_settings.KAFKA_ENABLE_AUTO_OFFSET_STORE | quote }}
  KAFKA_MAX_POLL_INTERVAL_MS: {{ .Values.ocr_api_gateway_settings.KAFKA_MAX_POLL_INTERVAL_MS | quote }}
  {{ if .Values.ocr_api_gateway_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.ocr_api_gateway_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.ocr_api_gateway_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}
  TESSERACT_URL: {{ .Values.ocr_api_gateway_settings.TESSERACT_URL | quote }}
  AWS_TEXTRACT_URL: {{ .Values.ocr_api_gateway_settings.AWS_TEXTRACT_URL | quote }}
  GCP_VISION_URL: {{ .Values.ocr_api_gateway_settings.GCP_VISION_URL | quote }}
  AZURE_FORM_RECOGNIZER_URL: {{ .Values.ocr_api_gateway_settings.AZURE_FORM_RECOGNIZER_URL | quote }}
  FILE_STORAGE_URL: {{ .Values.ocr_api_gateway_settings.FILE_STORAGE_URL | quote }}
  OCR_GATEWAY_URL: {{ .Values.ocr_api_gateway_settings.OCR_GATEWAY_URL | quote }}
  TESSERACT_ENABLED: {{ .Values.ocr_api_gateway_settings.TESSERACT_ENABLED | quote }}
  GCP_VISION_ENABLED: {{ .Values.ocr_api_gateway_settings.GCP_VISION_ENABLED | quote }}
  AWS_TEXTRACT_ENABLED: {{ .Values.ocr_api_gateway_settings.AWS_TEXTRACT_ENABLED | quote }}
  AZURE_FORM_RECOGNIZER_ENABLED: {{ .Values.ocr_api_gateway_settings.AZURE_FORM_RECOGNIZER_ENABLED | quote }}
  TESSERACT_TIMEOUT: {{ .Values.ocr_api_gateway_settings.TESSERACT_TIMEOUT | quote }}
  GCP_VISION_TIMEOUT: {{ .Values.ocr_api_gateway_settings.GCP_VISION_TIMEOUT | quote }}
  AWS_TEXTRACT_TIMEOUT: {{ .Values.ocr_api_gateway_settings.AWS_TEXTRACT_TIMEOUT | quote }}
  AZURE_FORM_RECOGNIZER_TIMEOUT: {{ .Values.ocr_api_gateway_settings.AZURE_FORM_RECOGNIZER_TIMEOUT | quote }}
  {{ if .Values.ocr_api_gateway_settings.message_broker_asb_without_manage_permission }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.ocr_api_gateway_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  ASB_TOPIC_NAME: '{{ .Values.ocr_api_gateway_settings.ASB_TOPIC_NAME }}'