{{- if .Values.ocr_api_gateway.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: ocr
  labels:
    {{- include "deps-ocr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ocr_api_gateway.service.type }}
  ports:
    - port: {{ .Values.ocr_api_gateway.service.port }}
      targetPort: {{ .Values.ocr_api_gateway.container.portname }}
      protocol: {{ .Values.ocr_api_gateway.service.protocol }}
      name: {{ .Values.ocr_api_gateway.service.portname }}
  selector:
    {{- include "deps-ocr.selectorLabels" . | nindent 4 }}
{{- end }}
